apiVersion: apps/v1
kind: Deployment
metadata:
  name: server1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server1
  template:
    metadata:
      labels:
        app: server1
    spec:
      containers:
      - name: server1
        image: codewithcrazy/t-server1:latest
        ports:
        - containerPort: 3001
        volumeMounts:
        - name: log-volume
          mountPath: /usr/src/app/server1.log
      volumes:
      - name: log-volume
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: server1-service
spec:
  selector:
    app: server1
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30008 
  type: NodePort 
