apiVersion: apps/v1
kind: Deployment
metadata:
  name: server1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server1
  template:
    metadata:
      labels:
        app: server1
    spec:
      containers:
      - name: server1-container
        image: codewithcrazy/t-server1:latest
        ports:
        - containerPort: 3001  # Match this with the actual port used by your application
        # livenessProbe:
        #   httpGet:
        #     path: /hi
        #     port: 3001  # Ensure this matches the actual listening port
        #     scheme: HTTPS  # Use HTTPS since your server expects it
        #   initialDelaySeconds: 15
        #   timeoutSeconds: 5
        #   periodSeconds: 10
        #   failureThreshold: 3
        # readinessProbe:
        #   httpGet:
        #     path: /hi
        #     port: 3001  # Ensure this matches the actual listening port
        #     scheme: HTTPS  # Use HTTPS since your server expects it
        #   initialDelaySeconds: 15
        #   timeoutSeconds: 5
        #   periodSeconds: 10
        #   failureThreshold: 3
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: server1-service
spec:
  selector:
    app: server1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
      nodePort: 30008
  type: NodePort
